### PR TITLE
Fix Disconnect.Code Can't UnMarshal from JSON data fixes 

### LINKED ISSUE #117: Custom disconnect code invalid
https://github.com/centrifugal/centrifuge/blob/d24832cd40bb5b6103f3ba2a33c146597f286363/disconnect.go#L9
```go
type Disconnect struct {
	// Code is disconnect code.
	Code int `json:"-"`
	// Reason is a short description of disconnect.
	Reason string `json:"reason"`
	// Reconnect gives client an advice to reconnect after disconnect or not.
	Reconnect bool `json:"reconnect"`
}
```
document, we can return a custom broken link error
https://centrifugal.github.io/centrifugo/server/proxy/#return-custom-disconnect

But the code that actually returns forever is 0 because JSON data is ignored here.
Why should our Code field ignored from json ?

### PR DESCRIPTION
**Pull request by xjtdy888**
fixes #117

### CODE REVIEW

**Comment by FZambia** [comment]
@xjtdy888 hello, code ignored intentionally in JSON since it is sent as WebSocket close code - see [this line](https://github.com/centrifugal/centrifuge/blob/v0.8.0/handler_websocket.go#L137), so it's available on client side.

**Comment by xjtdy888** [comment]
Document: https://centrifugal.github.io/centrifugo/server/proxy/#return-custom-disconnect
The documentation describes how to custom disconnect, if JSON return is not accepted, there is no way for the actual backend to custom disconnect, because the code will always be 0 and gorilla/websocket ReadMessage will return the error ``invalid close code``` directly. 

In the centrifugal-go client library there will be no opportunity to get a custom disconnect error

https://github.com/centrifugal/centrifuge-go/blob/9794a386af66abc5ad05dea24233cd9e493505c2/transport_websocket.go#L112

```go
_, data, err := t.conn.ReadMessage()
		if err != nil {
			disconnect := extractDisconnectWebsocket(err)
			t.disconnect = disconnect
			return
		}
```

**Comment by FZambia** [comment]
You are right, but the actual fix should be in `centrifuge-go` library since `code` already available on client side as part of websocket CloseError - see `Code` field https://godoc.org/github.com/gorilla/websocket#CloseError

**Comment by xjtdy888** [comment]
When the back-end API response is a custom disconnect, centrifugal receives the response and the code is lost after unmarshal, which I don't think can be handled in the client library.

**Comment by FZambia** [comment]
See https://github.com/centrifugal/centrifuge-go/pull/33 - as I said code already sent to client so we only need to expose it in client API.

**Comment by FZambia** [comment]
See [this line](https://github.com/centrifugal/centrifuge/blob/master/handler_websocket.go#L137) in centrifuge library - look that we already send Code from `Disconnect` as part of Close frame.

**Comment by xjtdy888** [comment]
@FZambia Yes, we were able to send the code.
Please forgive my English.
maybe I didn't describe the problem clearly.
Please see this line:
https://github.com/centrifugal/centrifugo/blob/f1988703663ed487e29adddaceb714604a8f9487/internal/proxy/connect_http.go#L76
```go
type ConnectReply struct {
	Result     *ConnectCredentials    `json:"result"`
	Error      *centrifuge.Error      `json:"error"`
	Disconnect *centrifuge.Disconnect `json:"disconnect"`
}
```
The results of unmarall of the ConnectReply.Disconnect structure will not contain the value of code。

**Comment by FZambia** [comment]
@xjtdy888 yeah, so the problems comes from Centrifugo level... I think we need to also exclude Code from being duplicated in JSON payload when marshalled for Websocket Close frame, I suggest doing sth like this:

```
Code int `json:"code,omitempty"`
```

And then explicitly make Code as zero value before marshalling for Close frame so it won't become part of marshalled JSON.

**Comment by FZambia** [comment]
Unmarshalling should be fixed with https://github.com/centrifugal/centrifuge/commit/a35cfb50a4df3a69c606aea19a940f94babbaeef

**Pull request closed without merging**
